swagger: '2.0'
info:
  version: 0.0.4
  title: 'Cisco PSIRT openVuln API'
  description: |
    The Cisco Product Security Incident Response Team (PSIRT) openVuln API is a RESTful API that allows customers to obtain Cisco Security Vulnerability information in different machine-consumable formats. APIs are important for customers because they allow their technical staff and programmers to build tools that help them do their job more effectively (in this case, to keep up with security vulnerability information).
    For more information about the Cisco PSIRT openVuln API visit https://developer.cisco.com/site/PSIRT/discover/overview

    For detail steps on how to use the API go to: https://developer.cisco.com/site/PSIRT/get-started/getting-started.gsp

    This is a beta release of a swagger YAML for the Cisco PSIRT openVuln API

    To access the API sign in with your Cisco CCO account at http://apiconsole.cisco.com and register an application
    to recieve a client_id and a client_secret

    You can then get your token using curl or any other method you prefer.

    'curl -s -k -H "Content-Type: application/x-www-form-urlencoded" -X POST -d "client_id=<your_client_id>" -d "client_secret=<your_client_secret>" -d "grant_type=client_credentials" https://cloudsso.cisco.com/as/token.oauth2'

    You will receive an access token as demonstrated in the following example:
     '{"access_token":"I7omWtBDAieSiUX3shOxNJfuy4J6","token_type":"Bearer","expires_in":3599}'

    In Swagger, click on Change Authentication

    enter the text "I7omWtBDAieSiUX3shOxNJfuy4J6" (which is the token you received)

    then click on "Try this operation"
  contact:
    name: Omar Santos
    email: os@cisco.com
schemes:
 - https
host: api.cisco.com

securityDefinitions:
  psirt_openvuln_api_auth:
    type: oauth2
    flow: implicit
    authorizationUrl: 'https://cloudsso.cisco.com/as/token.oauth2'
    scopes:
        'read:advisories': read advisories

produces:
  - application/json

paths:
  /security/advisories/all:
    get:
      description: >
        Used to obtain information about all published security advisories. By default the output is in JSON. To obtain the output in XML use the .xml extension. For example, /advisories/all.xml
      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response


  /security/advisories/cve/{cve_id}:
    get:
      description: >
        Used to obtain an advisory using a given Common
        Vulnerability Enumerator (CVE). The `cve_id` format is CVE-YYYY-NNNN. For
        more information about CVE visit http://cve.mitre.org/
      parameters:
        - name: cve_id
          in: path
          description: 'CVE Identifier (i.e., CVE-YYYY-NNNN)'
          required: true
          type: string
          format: CVE-YYYY-NNNN
      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response

  /security/advisories/advisory/{advisory_id}:
    get:
      description: >
        Used to obtain an advisory given its advisory ID
        `advisory_id` (i.e., cisco-sa-20180221-ucdm)
      parameters:
        - name: advisory_id
          in: path
          description: advisory ID
          required: true
          type: string
          format: cisco-sa-XXX
      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response

  /security/advisories/severity/{severity}:
    get:
      description: >
        Used to obtain all security advisories for a given security impact rating
        (critical, high, medium, or low).
      parameters:
        - name: severity
          in: path
          description: Critical, High, Medium, Low
          required: true
          type: string
          enum:
            - critical
            - high
            - medium
            - low
          format: enum
      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response
  /security/advisories/severity/{severity}/lastpublished:
    get:
      description: >
        Used to obtain all security advisories for a given security impact rating
        (critical, high, medium, or low).
      parameters:
        - name: severity
          in: path
          description: Used to obtain all advisories that have a security impact rating of critical
          required: true
          type: string
          enum:
            - critical
            - high
            - medium
            - low
          format: enum
        - name: startDate
          in: query
          required: true
          type: string
          format: date
        - name: endDate
          in: query
          required: true
          type: string
          format: date

      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response
  /security/advisories/severity/{severity}/firstpublished:
    get:
      description: >
        Used to obtain all security advisories for a given security impact rating
        (critical, high, medium, or low) and additionally filter based of firstpublished
        start date and enddate.
      parameters:
        - name: severity
          in: path
          description: Used to obtain all advisories that have a security impact rating of critical
          required: true
          type: string
          enum:
            - critical
            - high
            - medium
            - low
          format: enum
        - name: startDate
          in: query
          required: true
          type: string
          format: date
        - name: endDate
          in: query
          required: true
          type: string
          format: date

      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response
  /security/advisories/year/{year}:
    get:
      description: >
        Used to obtain all security advisories that have were orginally published
        in a specific year `YYYY`.
      parameters:
        - name: year
          in: path
          description: The four digit year.
          required: true
          type: string
          format: YYYY
      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response

  /security/advisories/latest/{number}:
    get:
      description: >
        Used to obtain all the latest security advisories given an
        absolute number. For instance, the latest 10 or latest 5.
      parameters:
        - name: number
          in: path
          description: An absolute number to obtain the latest security advisories.
          required: true
          type: integer
          format: number
      security:
       - psirt_openvuln_api_auth:
           - 'read:advisories'
      responses:
        '200':
          description: Successful response

  /security/advisories/product:
    get:
      description: >
        Used to obtain all the advisories that affects the given product name.
      parameters:
        - name: product
          in: query
          description: An product name to obtain security advisories that matches given product name.
          required: true
          type: string
          format: string
      security:
        - psirt_openvuln_api_auth:
          - 'read:advisories'
      responses:
        '200':
          description: Successful response
  /security/advisories/ios:
    get:
      description: >
        Used to obtain all advisories that affects the given ios version
      parameters:
        - name: version
          in: query
          description: IOS version to obtain security advisories
          required: true
          type: string
          format: string
      security:
        - psirt_openvuln_api_auth:
          - 'read:advisories'
      responses:
        '200':
          description: Successful response
  /security/advisories/iosxe:
    get:
      description: >
        Used to obtain all advisories that affects the given ios version
      parameters:
        - name: version
          in: query
          description: IOS version to obtain security advisories
          required: true
          type: string
          format: string
      security:
        - psirt_openvuln_api_auth:
          - 'read:advisories'
      responses:
        '200':
          description: Successful response
